- name : check apache and install apache
  yum:
    name: "{{ package_name }}"
    state: latest
    update_cache: yes

- name: check the serice and make sure it is in started state
  service:
    name: "{{ package_name }}"
    enabled: yes
    state: started
